#!/usr/bin/env python3
"""I-21.4: Build the per-asset regime multiplier table.

Method (user decisions: per-asset multiplier, mean-ratio, anchor-date
regime, 5-day persistence gate):

    For each asset, each COMPLETED BTC halving-cycle drawdown (from
    alt_cycle_metrics.csv, drawdown_asset_pct) is attributed to the
    gated regime_state in force on the asset's local top date (the
    drawdown onset -- consistent with round-2 H8/H10 methodology).

    multiplier(asset, R) = mean(drawdown | regime==R) / mean(all drawdowns)

    A multiplier > 1 means the regime's bear drawdowns are deeper than
    the asset's unconditional average -> the regime-adjusted B4 price
    band is scaled DOWN (price_low/high divided by the multiplier).

    Fallback: if fewer than MIN_SAMPLES (3) observed drawdowns fall in
    regime R for the asset, multiplier = 1.0 with multiplier_source =
    'fallback_to_1.0' (flagged, not silently assumed). This is the
    honest small-sample default from the I-21 plan; the white paper
    reports multiplier_source per asset/regime.

    Bounds: computed multipliers are clamped to [0.5, 2.0] (a 50%-200%
    band) to keep a tiny-sample estimate from blowing up the B4 band.

Output: data/processed/regime_multipliers.csv
  asset, regime_state, drawdown_cond_mean, drawdown_uncond_mean,
  multiplier, n_samples, multiplier_source
plus a data/processed/regime_anchor.csv row capturing the latest
regime_state and its days-in-effect (anchor for the B4 projection).
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
PROC = ROOT / "data" / "processed"

MIN_SAMPLES = 3
MULT_MIN, MULT_MAX = 0.5, 2.0

REGIME_COLS = ["normal", "bull_steep", "bear_steep", "inverted_flat"]
ASSET_ORDER = ["btc", "eth", "xrp", "sol", "mstr", "wgmi", "mara",
               "spx", "ndx", "dxy", "tlt", "gold"]


def _write_sensitivity_include(out: pd.DataFrame, anchor: pd.Series) -> None:
    """Emit _includes/regime-sensitivity.html (Jekyll include).

    Renders the full per-asset x per-regime multiplier table so the
    decision-interval counterfactuals are visible: every cell shows the
    multiplier, the sample count, and a computed/fallback badge. Cells
    with no observed drawdown onset in that regime show an em dash.
    The anchor-regime column is highlighted (it is the one in force
    today).
    """
    assets = [a for a in ASSET_ORDER if a in set(out["asset"])]
    extra = sorted(set(out["asset"]) - set(ASSET_ORDER))
    assets += extra

    def _cell(asset: str, regime: str) -> str:
        row = out[(out["asset"] == asset) & (out["regime_state"] == regime)]
        if row.empty:
            return "<td class=\"rs-empty\">\u2014</td>"
        r = row.iloc[0]
        badge = ("computed" if r["multiplier_source"] == "computed"
                 else "fallback")
        cls = "rs-computed" if r["multiplier_source"] == "computed" else "rs-fallback"
        return (f"<td class=\"{cls}\">\u00d7{r['multiplier']:.2f} "
                f"<span class=\"rs-n\">n={int(r['n_samples'])}</span> "
                f"<span class=\"rs-badge\">{badge}</span></td>")

    lines = [
        "<!-- AUTO-GENERATED by scripts/build_regime_multipliers.py -- do not edit -->",
        "<div class=\"regime-sensitivity\">",
        f"<p class=\"rs-anchor\"><b>Anchor regime:</b> {anchor['regime_state']} "
        f"(\u00d7 highlighted column; since {anchor['anchor_date']}, "
        f"{int(anchor['regime_state_days'])}d in effect). Multiplier = "
        "mean(drawdown | regime) / mean(all drawdowns), attributed at each "
        "asset's local top date. <b>Computed</b> only at n\u22653 observed "
        "drawdowns; otherwise flagged <b>fallback</b> \u00d71.00 \u2014 the B4 "
        "corridor stands on its unconditional cycle statistics.</p>",
        "<table>",
        "<thead><tr><th>Asset</th>",
    ]
    for regime in REGIME_COLS:
        hl = " class=\"rs-anchor-col\"" if regime == anchor["regime_state"] else ""
        lines.append(f"<th{hl}>{regime}</th>")
    lines.append("</tr></thead><tbody>")
    for asset in assets:
        label = asset.upper() if len(asset) <= 4 else asset.upper()
        lines.append(f"<tr><th>{label}</th>")
        for regime in REGIME_COLS:
            lines.append(_cell(asset, regime))
        lines.append("</tr>")
    lines += ["</tbody></table>", "</div>"]

    inc_dir = ROOT / "_includes"
    inc_dir.mkdir(exist_ok=True)
    path = inc_dir / "regime-sensitivity.html"
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {path}")


def main(argv: list[str] | None = None) -> int:
    cm = pd.read_csv(PROC / "alt_cycle_metrics.csv", parse_dates=["asset_local_top_date"])
    btc_m = pd.read_csv(PROC / "btc_cycle_metrics.csv")
    curve = pd.read_csv(PROC / "curve_state.csv", parse_dates=["date"]).set_index("date")

    # BTC joins the table (user decision: anchor asset must be adjustable
    # too). Its metrics use final_top_date/drawdown_pct; normalize to the
    # alt schema so one code path attributes all drawdowns.
    bt = btc_m.dropna(subset=["final_top_date", "drawdown_pct"]).copy()
    bt = bt[bt["drawdown_pct"] != ""]
    bt["asset"] = "btc"
    bt["asset_local_top_date"] = pd.to_datetime(bt["final_top_date"])
    bt["drawdown_asset_pct"] = pd.to_numeric(bt["drawdown_pct"], errors="coerce")
    cm = pd.concat([cm, bt], ignore_index=True)

    # Regime on each drawdown onset (local top date). Reindex-forward to
    # nearest regime day <= top date (handles holidays/weekends).
    curve_sorted = curve.sort_index()
    tops = cm.dropna(subset=["asset_local_top_date", "drawdown_asset_pct"]).copy()
    tops["regime_state"] = (
        curve_sorted["regime_state"].reindex(tops["asset_local_top_date"], method="ffill").values
    )
    tops = tops.dropna(subset=["regime_state"])
    tops = tops[tops["regime_state"] != "unclassified"]

    rows = []
    for asset, grp in tops.groupby("asset"):
        uncond = grp["drawdown_asset_pct"].mean()
        for regime, sub in grp.groupby("regime_state"):
            n = len(sub)
            cond = sub["drawdown_asset_pct"].mean()
            if n >= MIN_SAMPLES:
                mult = cond / uncond if uncond > 0 else 1.0
                mult = min(max(mult, MULT_MIN), MULT_MAX)
                source = "computed"
            else:
                mult = 1.0
                source = "fallback_to_1.0"
            rows.append({
                "asset": asset,
                "regime_state": regime,
                "drawdown_cond_mean": round(cond, 6),
                "drawdown_uncond_mean": round(uncond, 6),
                "multiplier": round(mult, 6),
                "n_samples": n,
                "multiplier_source": source,
            })

    out = pd.DataFrame(rows).sort_values(["asset", "regime_state"]).reset_index(drop=True)

    # Anchor regime = latest gated regime in curve_state.csv
    latest = curve_sorted.iloc[-1]
    anchor_state = latest["regime_state"]
    anchor_date = latest.name.date().isoformat()

    # Ensure every asset resolves a multiplier for the ANCHOR regime so the
    # B4 integration never misses a row. If the asset has no observed
    # drawdown starting in the anchor regime, emit an explicit fallback row
    # (n=0, source=fallback_to_1.0) -- flagged, never silently assumed.
    for asset in tops["asset"].unique():
        has = ((out["asset"] == asset) & (out["regime_state"] == anchor_state)).any()
        if not has:
            grp = tops[tops["asset"] == asset]
            uncond = grp["drawdown_asset_pct"].mean() if len(grp) else 0.0
            out = pd.concat([
                out,
                pd.DataFrame([{
                    "asset": asset,
                    "regime_state": anchor_state,
                    "drawdown_cond_mean": 0.0,
                    "drawdown_uncond_mean": round(uncond, 6),
                    "multiplier": 1.0,
                    "n_samples": 0,
                    "multiplier_source": "fallback_to_1.0",
                }]),
            ], ignore_index=True)
    out = out.sort_values(["asset", "regime_state"]).reset_index(drop=True)
    out.to_csv(PROC / "regime_multipliers.csv", index=False)

    anchor = pd.DataFrame([{
        "anchor_date": anchor_date,
        "regime_state": anchor_state,
        "regime_state_days": int(latest["regime_state_days"]),
        "prev_regime_state": latest["prev_regime_state"],
    }])
    anchor.to_csv(PROC / "regime_anchor.csv", index=False)

    _write_sensitivity_include(out, anchor.iloc[0])

    print(f"Wrote {PROC / 'regime_multipliers.csv'}  ({len(out)} rows)")
    print(f"Wrote {PROC / 'regime_anchor.csv'}  ({anchor.iloc[0]['anchor_date']} -> "
          f"{anchor.iloc[0]['regime_state']})")
    print("\nMultiplier table (asset, regime, mult, n, source):")
    for _, r in out.iterrows():
        print(f"  {r['asset']:5s} {r['regime_state']:14s} x{r['multiplier']:.3f} "
              f"(n={r['n_samples']}, {r['multiplier_source']})")
    n_computed = int((out["multiplier_source"] == "computed").sum())
    print(f"\n  computed multipliers: {n_computed} / {len(out)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())